//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Art_goods.Goods
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int idBasket { get; set; }
        public int IdUser { get; set; }
        public int IdGoods { get; set; }
    
        public virtual Goods_Art Goods_Art { get; set; }
        public virtual Users Users { get; set; }
    }
}
